version: "3.9"

services:
  db:
    image: postgres:15
    container_name: dbmeetstack
    restart: always
    # Credenciales y configuración de la base de datos para SOLO EL ENTORNO LOCAL
    environment:
      POSTGRES_DB: dbmeetstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5544:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
