name: CI

# Se dispara en cada push o PR a main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) bajar el código
      - uses: actions/checkout@v4

      # 2) preparar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3) instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) ejecutar tests
      - name: Check code style with ruff
        run: ruff check .

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
