name: CI/CD

# Se dispara en cada push o PR a main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      # 1) bajar el código
      - uses: actions/checkout@v4

      # 2) preparar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3) instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Check code style with ruff
        run: ruff check .

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
  ## ahora le sumo el cd usando los secret de github
  deploy:
    name: 🚀 CD- Deploy to Render
    needs: test
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Deploy to Render
        run: |
          echo "Calling Render deploy hook…"
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
